import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import Provider from "../providers";
import { Navbar } from "./navbar";
import Sidebar from "./sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Provider>
      <div className={cn(inter.className)}>
        <header className="sticky top-0 z-50 w-full border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60 hover:bg-slate-100">
          <Navbar />
        </header>
        <div className="hidden space-y-6 p-10 pb-16 md:block">
          <div className="flex flex-col space-y-8 lg:flex-row lg:space-x-12 lg:space-y-0">
            <aside className="-mx-4 lg:w-1/5">
              <Sidebar />
            </aside>
            <div className="flex-1 lg:max-w-full">{children}</div>
          </div>
        </div>
      </div>
    </Provider>
  );
}
